# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TaskService.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'TaskService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11TaskService.proto\x12\x04task\"\x07\n\x05\x45mpty\"c\n\nTaskCreate\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x42\x05\n\x03_id\"w\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x12\x11\n\tcreatedAt\x18\x06 \x01(\t\x12\x11\n\tupdatedAt\x18\x07 \x01(\t\"%\n\x08ListTask\x12\x19\n\x05tasks\x18\x01 \x03(\x0b\x32\n.task.Task\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\x96\x01\n\x0bTaskService\x12.\n\nCreateTask\x12\x10.task.TaskCreate\x1a\x0e.task.Response\x12&\n\x07GetTask\x12\x0b.task.Empty\x1a\x0e.task.ListTask\x12/\n\x0bUpdatedTask\x12\x10.task.TaskCreate\x1a\x0e.task.ResponseB<\n\x16\x63om.taskservice.protosB\x10TaskServiceProtoZ\x10task/taskserviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TaskService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.taskservice.protosB\020TaskServiceProtoZ\020task/taskservice'
  _globals['_EMPTY']._serialized_start=27
  _globals['_EMPTY']._serialized_end=34
  _globals['_TASKCREATE']._serialized_start=36
  _globals['_TASKCREATE']._serialized_end=135
  _globals['_TASK']._serialized_start=137
  _globals['_TASK']._serialized_end=256
  _globals['_LISTTASK']._serialized_start=258
  _globals['_LISTTASK']._serialized_end=295
  _globals['_REQUEST']._serialized_start=297
  _globals['_REQUEST']._serialized_end=320
  _globals['_RESPONSE']._serialized_start=322
  _globals['_RESPONSE']._serialized_end=349
  _globals['_TASKSERVICE']._serialized_start=352
  _globals['_TASKSERVICE']._serialized_end=502
# @@protoc_insertion_point(module_scope)
