# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserService.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'UserService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11UserService.proto\x12\x04user\"\x07\n\x05\x45mpty\"c\n\x04User\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\tfirstname\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\tB\x05\n\x03_id\"%\n\x08ListUser\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User\"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8b\x01\n\x0bUserService\x12\'\n\x08GetUsers\x12\x0b.user.Empty\x1a\x0e.user.ListUser\x12(\n\nCreateUser\x12\n.user.User\x1a\x0e.user.Response\x12)\n\x0bUpdatedUser\x12\n.user.User\x1a\x0e.user.ResponseB<\n\x16\x63om.userservice.protosB\x10UserServiceProtoZ\x10task/userserviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.userservice.protosB\020UserServiceProtoZ\020task/userservice'
  _globals['_EMPTY']._serialized_start=27
  _globals['_EMPTY']._serialized_end=34
  _globals['_USER']._serialized_start=36
  _globals['_USER']._serialized_end=135
  _globals['_LISTUSER']._serialized_start=137
  _globals['_LISTUSER']._serialized_end=174
  _globals['_REQUEST']._serialized_start=176
  _globals['_REQUEST']._serialized_end=199
  _globals['_RESPONSE']._serialized_start=201
  _globals['_RESPONSE']._serialized_end=228
  _globals['_USERSERVICE']._serialized_start=231
  _globals['_USERSERVICE']._serialized_end=370
# @@protoc_insertion_point(module_scope)
